require('./align.test')
require('./box.test')
require('./position.test')
require('./text.test')
require('./size.test')
require('./width.test')
require('./height.test')
require('./func.test')
require('./imports.test')
require('./row.test')
require('./col.test')
require('./variable.test')

require('./fullRender.test')